export const NOTIFICATION_CATEGORIES = {
  FRIGATE_ALERT: "FRIGATE_ALERT",
  FRIGATE_LIVE: "FRIGATE_LIVE",
  FRIGATE_GUARD: "FRIGATE_GUARD",
} as const;

export const NOTIFICATION_ACTIONS = {
  VIEW_CLIP: "VIEW_CLIP",
  MARK_REVIEWED: "MARK_REVIEWED",
  VIEW_LIVE: "VIEW_LIVE",
  SILENCE_30: "SILENCE_30",
  OPEN_HUB: "OPEN_HUB",
} as const;
