import SwiftUI

struct ReviewRow: View {
    @EnvironmentObject private var appState: AppState
    let review: FrigateReviewItem

    var body: some View {
        HStack(spacing: 12) {
            // Thumbnail — the cropped detection image (always generated by Frigate)
            ZStack(alignment: .bottomLeading) {
                if let url = appState.client?.reviewThumbnailURL(review: review) {
                    RemoteImage(url: url)
                        .frame(width: 80, height: 80)
                        .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
                } else {
                    RoundedRectangle(cornerRadius: 14, style: .continuous)
                        .fill(Color.white.opacity(0.08))
                        .frame(width: 80, height: 80)
                        .overlay(
                            Image(systemName: review.severity == "alert" ? "bell.badge.fill" : "scope")
                                .font(.system(size: 22, weight: .black))
                                .foregroundStyle(review.severity == "alert" ? GlassTheme.orange : GlassTheme.cyan)
                        )
                }
                // severity badge
                Text(review.severity == "alert" ? "ALERT" : "DETECT")
                    .font(.system(size: 8, weight: .black))
                    .foregroundStyle(.black)
                    .padding(.horizontal, 5)
                    .padding(.vertical, 2)
                    .background(review.severity == "alert" ? GlassTheme.orange : GlassTheme.cyan, in: Capsule())
                    .padding(4)
            }

            VStack(alignment: .leading, spacing: 5) {
                // Object + sub-label together ("Person — Alex"); the subtitle below
                // carries camera + zone, so the sub-label isn't repeated.
                Text(NotificationCopy.combinedTitle(for: review))
                    .font(.system(size: 15, weight: .black))
                    .foregroundStyle(GlassTheme.primary)
                    .lineLimit(1)
                Text(subtitle)
                    .font(.system(size: 12, weight: .bold))
                    .foregroundStyle(GlassTheme.secondary)
                    .lineLimit(2)
                if let epoch = review.startTime {
                    Text(Date(timeIntervalSince1970: epoch).formatted(date: .abbreviated, time: .shortened))
                        .font(.system(size: 11, weight: .bold))
                        .foregroundStyle(GlassTheme.tertiary)
                        .lineLimit(1)
                }
            }

            Spacer()

            if let count = review.data?.detections?.count, count > 0 {
                Text("\(count)")
                    .font(.system(size: 12, weight: .black))
                    .foregroundStyle(.black)
                    .padding(.horizontal, 9)
                    .padding(.vertical, 6)
                    .background(GlassTheme.cyan, in: Capsule())
                    .accessibilityLabel("\(count) detections")
            }
        }
        .padding(10)
        .background(.white.opacity(0.07), in: RoundedRectangle(cornerRadius: 20, style: .continuous))
        .accessibilityElement(children: .combine)
    }

    /// Camera + zone (the sub-label already lives in the title).
    private var subtitle: String {
        var parts = [titleize(review.camera)]
        if let zones = review.data?.zones, !zones.isEmpty {
            parts.append("Zone: " + zones.map(titleize).joined(separator: ", "))
        }
        return parts.joined(separator: " • ")
    }
}
