const LABEL_EMOJI: Record<string, string> = {
  person: "🧑",
  car: "🚗",
  dog: "🐕",
  cat: "🐈",
  bird: "🐦",
  bicycle: "🚲",
  motorcycle: "🏍️",
  truck: "🚛",
  bus: "🚌",
  horse: "🐎",
  sheep: "🐑",
  cow: "🐄",
  elephant: "🐘",
  bear: "🐻",
  zebra: "🦓",
  giraffe: "🦒",
  backpack: "🎒",
  umbrella: "☂️",
  handbag: "👜",
  tie: "👔",
  suitcase: "🧳",
  frisbee: "🥏",
  skis: "🎿",
  snowboard: "🏂",
  "sports ball": "⚽",
  kite: "🪁",
  "baseball bat": "⚾",
  "baseball glove": "🧤",
  skateboard: "🛹",
  surfboard: "🏄",
  "tennis racket": "🎾",
  bottle: "🍾",
  "wine glass": "🍷",
  cup: "☕",
  fork: "🍴",
  knife: "🔪",
  spoon: "🥄",
  bowl: "🥣",
  banana: "🍌",
  apple: "🍎",
  sandwich: "🥪",
  orange: "🍊",
  broccoli: "🥦",
  carrot: "🥕",
  "hot dog": "🌭",
  pizza: "🍕",
  donut: "🍩",
  cake: "🎂",
  chair: "🪑",
  couch: "🛋️",
  "potted plant": "🪴",
  bed: "🛏️",
  "dining table": "🍽️",
  toilet: "🚽",
  tv: "📺",
  laptop: "💻",
  mouse: "🖱️",
  remote: "📱",
  keyboard: "⌨️",
  "cell phone": "📱",
  microwave: "📦",
  oven: "🍳",
  toaster: "🍞",
  sink: "🚿",
  refrigerator: "🧊",
  book: "📚",
  clock: "⏰",
  vase: "💐",
  scissors: "✂️",
  "teddy bear": "🧸",
  "hair drier": "💨",
  toothbrush: "🪥",
  package: "📦",
  amazon: "📦",
  fedex: "📦",
  ups: "📦",
  usps: "📬",
};

export function getLabelEmoji(label: string): string {
  return LABEL_EMOJI[label.toLowerCase()] ?? "📷";
}

export function formatLabel(label: string): string {
  return label
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

export function getLabelColor(label: string): string {
  const colors: Record<string, string> = {
    person: "#3b82f6",
    car: "#f59e0b",
    dog: "#10b981",
    cat: "#8b5cf6",
    bird: "#06b6d4",
    bicycle: "#ec4899",
    motorcycle: "#f97316",
    truck: "#84cc16",
  };
  return colors[label.toLowerCase()] ?? "#64748b";
}
