import Foundation
import WidgetKit

/// Lets the widget pull fresh data from Frigate on its own timeline schedule, so it
/// updates in the background instead of only when the app is opened. Reads the
/// base URL + token the app mirrors into the app group (same ones the notification
/// extension uses), fetches recent un-reviewed alerts + a hero thumbnail, and writes
/// them into SharedSnapshotStore. On any failure it leaves the last cache untouched.
enum WidgetDataFetcher {
    private static var appGroup: UserDefaults? { UserDefaults(suiteName: ApexAppGroup.identifier) }

    private struct WReview: Decodable {
        let id: String
        let camera: String
        let severity: String?
        let startTime: Double?
        let hasBeenReviewed: Bool?
        let data: WReviewData?
    }

    private struct WReviewData: Decodable {
        let objects: [String]?
        let subLabels: [String]?
        let detections: [String]?
        let zones: [String]?
    }

    static func refresh() async {
        guard let defaults = appGroup,
              let base = defaults.string(forKey: "apex.frigateBaseURL"),
              let baseURL = URL(string: base) else { return }
        // Token from the shared Keychain group (no longer plaintext in the App-Group plist);
        // nil simply yields an unauthenticated request, same as before.
        let token = SharedTokenStore.load()

        guard var comps = URLComponents(
            url: baseURL.appendingPathComponent("api/review"),
            resolvingAgainstBaseURL: false
        ) else { return }
        comps.queryItems = [
            URLQueryItem(name: "limit", value: "8"),
            URLQueryItem(name: "reviewed", value: "0")
        ]
        guard let url = comps.url else { return }

        guard let data = await get(url, token: token) else { return }

        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        guard let reviews = try? decoder.decode([WReview].self, from: data) else { return }

        let unreviewed = reviews.filter { !($0.hasBeenReviewed ?? false) }
        let alerts: [SharedAlert] = unreviewed
            .prefix(8)
            .map { r in
                SharedAlert(
                    id: r.id,
                    label: r.data?.objects?.first ?? "object",
                    subLabel: r.data?.subLabels?.first,
                    camera: r.camera,
                    severity: r.severity ?? "alert",
                    when: Date(timeIntervalSince1970: r.startTime ?? Date().timeIntervalSince1970),
                    imageFileName: nil,
                    zone: r.data?.zones?.first
                )
            }

        guard !alerts.isEmpty else {
            // Nothing un-reviewed → show "all clear".
            SharedSnapshotStore.saveRecentAlerts([], heroImageData: nil)
            return
        }

        // Hero = the first detection's cropped thumbnail (always generated by Frigate).
        // Derive from the SAME filtered list as the caption, so image and text never
        // describe different events (the newest review may already be reviewed).
        var heroData: Data?
        if let detectionID = unreviewed.first?.data?.detections?.first {
            let thumbURL = baseURL.appendingPathComponent("api/events/\(detectionID)/thumbnail.jpg")
            heroData = await get(thumbURL, token: token)
        }

        SharedSnapshotStore.saveRecentAlerts(alerts, heroImageData: heroData)
    }

    private static func get(_ url: URL, token: String?) async -> Data? {
        var request = URLRequest(url: url)
        request.timeoutInterval = 8
        if let token, !token.isEmpty {
            request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
            request.setValue("frigate_token=\(token)", forHTTPHeaderField: "Cookie")
        }
        guard let (data, response) = try? await URLSession.shared.data(for: request),
              (response as? HTTPURLResponse).map({ (200..<300).contains($0.statusCode) }) ?? false else {
            return nil
        }
        return data
    }
}
